package com.zh.android.chat.service.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zh.android.chat.service.db.greendao.qr.entity.QrCodeScanHistoryEntity;

import com.zh.android.chat.service.db.greendao.QrCodeScanHistoryEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig qrCodeScanHistoryEntityDaoConfig;

    private final QrCodeScanHistoryEntityDao qrCodeScanHistoryEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        qrCodeScanHistoryEntityDaoConfig = daoConfigMap.get(QrCodeScanHistoryEntityDao.class).clone();
        qrCodeScanHistoryEntityDaoConfig.initIdentityScope(type);

        qrCodeScanHistoryEntityDao = new QrCodeScanHistoryEntityDao(qrCodeScanHistoryEntityDaoConfig, this);

        registerDao(QrCodeScanHistoryEntity.class, qrCodeScanHistoryEntityDao);
    }
    
    public void clear() {
        qrCodeScanHistoryEntityDaoConfig.clearIdentityScope();
    }

    public QrCodeScanHistoryEntityDao getQrCodeScanHistoryEntityDao() {
        return qrCodeScanHistoryEntityDao;
    }

}
